# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AdjustTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdjustTestApp
  pod 'Adjust', :path => '../../'
  pod 'AdjustTestLibrary', :path => '../AdjustTestLibrary/'
  pod 'AdjustTestOptionsLibrary', :path => '../AdjustTestOptionsLibrary/'

end
