# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AdjustExample-WebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdjustExample-WebView
#  pod 'Adjust', :path => '../../'

#  pod 'Adjust/Core', :path => '../../'
  pod 'Adjust/WebBridge', :path => '../../'

end
